// ============================================================
// Template Registry
// Maps DeviceRole → full Nunjucks device template string.
// To add a new role or protocol, add/modify entries here.
// ============================================================

import {
  INTERFACES_PARTIAL,
  PORT_CHANNELS_PARTIAL,
  SVI_PARTIAL,
  OSPF_PARTIAL,
  EIGRP_PARTIAL,
  BGP_PARTIAL,
  STATIC_ROUTES_PARTIAL,
  DHCP_PARTIAL,
  STP_PARTIAL,
  VTP_PARTIAL,
  SSH_PARTIAL,
  NTP_PARTIAL,
  VLAN_DB_PARTIAL,
} from "./partials";

import { DeviceRole } from "../types";

// Helpers to compose a full device config by concatenating partials
const section = (...parts: string[]) => parts.join("\n!\n");

// ------------------------------------------------------------------
// ROUTER template
// ------------------------------------------------------------------
const ROUTER_HEADER = [
  "!",
  "! ============================================================",
  "! Device: {{ hostname }}  |  Role: Router",
  "! Generated by NetAutoGen",
  "! ============================================================",
  "!",
  "hostname {{ hostname }}",
  "!",
  "no ip domain-lookup",
  "service password-encryption",
  "{% if enable_secret %}",
  "enable secret {{ enable_secret }}",
  "{% endif %}",
  "{% if banner %}",
  "banner motd # {{ banner }} #",
  "{% endif %}",
  "!",
].join("\n");

const ROUTER_TEMPLATE = [
  ROUTER_HEADER,
  INTERFACES_PARTIAL,
  OSPF_PARTIAL,
  EIGRP_PARTIAL,
  BGP_PARTIAL,
  STATIC_ROUTES_PARTIAL,
  DHCP_PARTIAL,
  NTP_PARTIAL,
  SSH_PARTIAL,
  "end",
].join("\n!\n");

// ------------------------------------------------------------------
// LAYER 3 SWITCH template
// ------------------------------------------------------------------
const L3_HEADER = [
  "!",
  "! ============================================================",
  "! Device: {{ hostname }}  |  Role: L3 Switch",
  "! Generated by NetAutoGen",
  "! ============================================================",
  "!",
  "hostname {{ hostname }}",
  "!",
  "no ip domain-lookup",
  "ip routing",
  "service password-encryption",
  "{% if enable_secret %}",
  "enable secret {{ enable_secret }}",
  "{% endif %}",
  "!",
].join("\n");

const L3_SWITCH_TEMPLATE = [
  L3_HEADER,
  VTP_PARTIAL,
  STP_PARTIAL,
  VLAN_DB_PARTIAL,
  INTERFACES_PARTIAL,
  PORT_CHANNELS_PARTIAL,
  SVI_PARTIAL,
  OSPF_PARTIAL,
  EIGRP_PARTIAL,
  BGP_PARTIAL,
  STATIC_ROUTES_PARTIAL,
  DHCP_PARTIAL,
  NTP_PARTIAL,
  SSH_PARTIAL,
  "end",
].join("\n!\n");

// ------------------------------------------------------------------
// LAYER 2 SWITCH template
// ------------------------------------------------------------------
const L2_HEADER = [
  "!",
  "! ============================================================",
  "! Device: {{ hostname }}  |  Role: L2 Switch",
  "! Generated by NetAutoGen",
  "! ============================================================",
  "!",
  "hostname {{ hostname }}",
  "!",
  "no ip domain-lookup",
  "service password-encryption",
  "{% if enable_secret %}",
  "enable secret {{ enable_secret }}",
  "{% endif %}",
  "!",
].join("\n");

const L2_SWITCH_TEMPLATE = [
  L2_HEADER,
  VTP_PARTIAL,
  STP_PARTIAL,
  VLAN_DB_PARTIAL,
  INTERFACES_PARTIAL,
  PORT_CHANNELS_PARTIAL,
  NTP_PARTIAL,
  SSH_PARTIAL,
  "end",
].join("\n!\n");

// ------------------------------------------------------------------
// FIREWALL template (basic IOS-style with NAT/ACL stubs)
// ------------------------------------------------------------------
const FW_HEADER = [
  "!",
  "! ============================================================",
  "! Device: {{ hostname }}  |  Role: Firewall",
  "! Generated by NetAutoGen",
  "! ============================================================",
  "!",
  "hostname {{ hostname }}",
  "!",
].join("\n");

const FIREWALL_TEMPLATE = [
  FW_HEADER,
  INTERFACES_PARTIAL,
  STATIC_ROUTES_PARTIAL,
  "end",
].join("\n!\n");

// ------------------------------------------------------------------
// Registry export
// ------------------------------------------------------------------
export const TEMPLATES: Record<DeviceRole, string> = {
  router: ROUTER_TEMPLATE,
  l3_switch: L3_SWITCH_TEMPLATE,
  l2_switch: L2_SWITCH_TEMPLATE,
  firewall: FIREWALL_TEMPLATE,
};
